### ISSUE TITLE
ERROR  The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'   import {PassThrough as PassThroughStream, getDefaultHighWaterMark} from 'node:stream';   ^^^^^^^^^^^^^^^^^^^^^^^   SyntaxError: The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'   at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)   at async ModuleJob.run (node:internal/modules/esm/module_job:190:5) error Command failed with exit code 1.

### ISSUE THREAD

**Issue by iford** [sindresorhus/merge-streams#16]
<img width="922" alt="Screenshot 2567-02-13 at 14 14 26" src="https://github.com/sindresorhus/merge-streams/assets/21168517/5ff3f619-3e43-44bb-be47-d7ca4614b2fc">

I solved the problem by this way.

	"resolutions": {
		"**/@sindresorhus/merge-streams": "2.1.0"
	}

**Comment by sindresorhus** [comment]
Sounds like you need to update your Node.js version.

**Comment by playable-dannie** [comment]
> Sounds like you need to update your Node.js version.

Thank you for the work on this package 🙏

But the package.json indicates that it supports 18 and above. If node 19 APIs are used, shouldn't it be reflected in the package.json at the very least? Usually, breaking changes promotes a major version - but i guess that is up to interpretation :)

**Comment by ehmicky** [comment]
[`getDefaultHighWaterMark()`](https://nodejs.org/api/stream.html#streamgetdefaulthighwatermarkobjectmode) is available in Node 18, more precisely `18.17.0`.

As a side note, you might want to shorten the GitHub issue title to a more concise one.

**Comment by ehmicky** [comment]
This was fixed in `2.2.1`.

**Comment by playable-dannie** [comment]
@ehmicky Awesome. Thank you 🙏
