### ISSUE TITLE
Dropped supporting node v18 in v2.2.0

### ISSUE THREAD

**Issue by Kassaila** [sindresorhus/merge-streams#17]
Hi.
I got an error when update my project today.

This function `getDefaultHighWaterMark` not exist in node v18.

Maybe package support for node v18 has been dropped?

**Comment by ehmicky** [comment]
Hi @Kassaila,
Please see [the following comment](https://github.com/sindresorhus/merge-streams/issues/16#issuecomment-1941848490).

**Comment by ehmicky** [comment]
This was fixed in `2.2.1`.
