### ISSUE TITLE
SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by emiltoteb** [sindresorhus/merge-streams#43]
```
.../@sindresorhus/merge-streams/index.js:60
                this.#onFinished ??= onMergedStreamFinished(this, this.#streams);
                                 ^^^

SyntaxError: Unexpected token '??='
```

———

This seems to be blocking execution and raising issues from dependents.

**Comment by ehmicky** [comment]
Hi @emiltoteb,

Which Node.js version are you using?
Also, which version of `merge-streams` are you using?

**Comment by emiltoteb** [comment]
And that's how you know it's already too late for proper work...

I've been switching between projects and got this specific one to use node v14.21.3
merge-streams v4.0.0

For anyone in a similar half-asleep state `??=` is supported starting Node 15.

Thanks @ehmicky!

**Comment by ehmicky** [comment]
Yes, this library only supports Node `>=18.18`.

See https://github.com/sindresorhus/merge-streams/releases/tag/v4.0.0

https://github.com/sindresorhus/merge-streams/blob/dad789407134980df2e1ad8387c9ead90a5965e2/package.json#L20
