### ISSUE TITLE
Error 404 Not Found

### ISSUE THREAD

**Issue by francescor-tuidi** [sindresorhus/merge-streams#45]
Hi,

after running 

`npm install @sindresorhus/merge-streams`

i get the following error:

```
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@sindresorhus%2fmerge-streams - Not found
npm error 404
npm error 404  '@sindresorhus/merge-streams@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-08T18_39_56_257Z-debug-0.log
```

npm version: 10.9.0

**Comment by ehmicky** [comment]
Hi @francescor-tuidi,

This is not just for this package. Every package is currently returning 404. You can confirm this by searching https://www.npmjs.com. 

This is due to a "scheduled infrastructure upgrade" of NPM: https://status.npmjs.org/incidents/px35z3dmcjgm

**Comment by francescor-tuidi** [comment]
Sorry for the opened issue. Thank you @ehmicky
